name: CI Checks

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install flake8
        run: pip install flake8

      - name: Run flake8
        run: |
          if ls **/*.py > /dev/null 2>&1; then
            flake8 .
          else
            echo "No Python files found, skipping."
          fi

  dockerfile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Hadolint
        run: |
          wget -qO /usr/local/bin/hadolint https://github.com/hadolint/hadolint/releases/download/v2.12.0/hadolint-Linux-x86_64
          chmod +x /usr/local/bin/hadolint

      - name: Lint Dockerfiles
        run: |
          if ls **/Dockerfile > /dev/null 2>&1; then
            hadolint **/Dockerfile
          else
            echo "No Dockerfiles found, skipping."
          fi
